---
title: "박소연 크롤링"
author: "Soyeon Park"
date: '2021 5 10 '
output: html_document
---

```{r}
library(rvest)
library(stringr)
library(dplyr)

```
## 0510 크롤링 과제 

#### 1. 한빛미디어 새로나온 책 목록 25페이지 전체 크롤링해서 .csv 형식으로 저장하기.\

###### 웹사이트 읽어오기
```{r}
base_url <- 'https://www.hanbit.co.kr/media/books/'
sub_url <- 'new_book_list.html'
url <- paste0(base_url, sub_url)
# 뒤에서 페이지 설정할거 하나 더 붙여야 하기 때문에 bese, sub url 설정 후 paste0 활용하여 sep = '/' 없이 url을 구성.
html <- read_html(url)


# 여기서부터 시작해도 됨.(sub_book_list <- html_node(html, '.sub_book_list_area'))
# 단, 이게 검색범위를 좁힐 수 있는 한계가 있음. 그걸 모르니까 일단 큰 거부터 시작하는 것도 좋다. 코드 몇줄 추가만 하면 되는 거니까

sub_book_list <- html_node(html, '.sub_book_list_area') 
lis <- html_nodes(sub_book_list, 'li')    

html_node(html, '.sub_book_list_area') %>% 
    html_nodes(sub_book_list, 'li')

```

###### for loop문으로 1페이지부터 25페이지까지 데이터 프레임 만들기(500개 데이터.)
```{r}
title_vector <- c()
writer_vector <- c()
page_vector <- c()
price_vector <- c()

# formatted string : %s 는 string, %d 는 정수, %f 는 실수.

for (i in 1:25) {
    page_url <- paste0('?page=', i)
    
    for (li in lis) {
        info <- html_node(li, '.info')
        title <- info %>% 
            html_node('.book_tit') %>% 
            html_text()
        writer <- info %>% 
            html_node('.book_writer') %>% 
            html_text()
        href <- li %>% 
            html_node('.info') %>% 
            html_node('a') %>% 
            html_attr('href')
            book_url <- paste0(base_url, href)     
#  paste(base_url, href, sep = '/')을 써도 되긴 됨(url이 이상하게 찍히는데 접속하는데 문제는 없음. 이유는 모름.)
        book_html <- read_html(book_url)
        info_list <- html_node(book_html, 'ul.info_list')
        book_lis <- html_nodes(info_list, 'li')
        for (book_li in book_lis) {
            item <- book_li %>% 
                html_node('strong') %>% 
                html_text()
            if (substring(item, 1, 3) == '페이지') {
                page <- book_li %>% 
                    html_node('span') %>% 
                    html_text()
                len <- str_length(page) 
                page <- as.integer(substring(page, 1, len-2))
                break
            }
        }
        pay_info <- html_node(book_html, '.payment_box.curr')
        ps <- html_nodes(pay_info, 'p')
        price <- ps[2] %>% 
            html_node('.pbr') %>% 
            html_node('strong') %>% 
            html_text()
        price <- as.integer(gsub(',','',price))
        
        title_vector <- c(title_vector, title)
        writer_vector <- c(writer_vector, writer)
        page_vector <- c(page_vector, page)
        price_vector <- c(price_vector, price)
    }
}

new_books <- data.frame(
    title=title_vector,
    writer=writer_vector,
    page=page_vector,
    price=price_vector
)
```

###### csv파일로 저장하기.

```{r}
# View(new_books)
# write.csv(new_books, "C:/workspace/R/data/new_books.csv")
```


























