---
title: "exercise"
author: "Soyeon Park"
date: '2021 4 21 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 연습문제 p.90
문제를 해결하시오.
```{r}
# 1번 문제

x <- c(1:5)
x <- c(x, c(6:10))

# 2번 문제

# 첫 번째 시도(seq from to by 문법)
x <- c(1:10)
x <- seq(from=2, to=10, by=2)    # 이렇게 해도 되는거 맞나?

# 두 번째 시도(length.out 활용한 방법)
x <- c(1:10)
x <- seq(2, 10, length.out = 5)   #?? 시작을 2부터 해도 되는건가?

# 세 번째 시도(홀수 값만을 저장하는 임의의 벡터 하나 만든 후 차집합(setdiff) 활용.)
x <- c(1:10)
S5 <- c(seq(1,9,2))
x <- c(setdiff(x,S5))             # 답은 완성하였으나 문제해결 코드가 2줄이 됨.

# 네 번째 시도(단순히 그냥 1~9까지 홀수 값 직접 입력하여 제외하고 출력)
x <- c(1:10)
x <- x[-c(1,3,5,7,9)]             # 답은 되지만... 이렇게 할거면 직접 손으로 쳤지...

# 다섯 번째 시도(%%연산자 통해 2로 나눈 나머지 0 ==로 좌우값 일치 체크 하여 짝수만 남기기.)
x <- c(1:10)
x <- x[x%%2==0]                       # 실수노트) 논리연산자 ==와 일반 등호 착각하지 않기.

# 답지...내가 1트 2트 한거랑 똑같이 한거 아닌가... 굳이 length로 쓰는 이유는 무엇이지
x <- c(1:10)
x <- x[seq(2,length(x),2)]
```
### 단원문제 p.112
```{r}

# 1번 문제
x <- c(1:100)
x <- x[x%%3==0]
y <- c(1:100)
y <- y[y%%4==0]

# 2번 문제
# R에서도 sum 함수를 사용할 수 있었다.. ㅠㅠ 
intersect(x, y)
sum(intersect(x, y))

```

