---
title: "Untitled"
author: "Soyeon Park"
date: '2021 4 22 '
output: html_document
---
# 단원문제 ch-03 (p.112)
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1번문제
```{r}
x <- c(1:100)
x <- x[x%%3==0]
y <- c(1:100)
y <- y[y%%4==0]
x
y
```

## 2번문제(답: 432)
```{r}
intersect(x, y)
sum(intersect(x,y))
```

## 3번문제

### 답: New York Air Quality Measurements

#### ?airqulity 하여 정보 확인.

## 4번문제

### 답: (답: numeric	Temperature (degrees F))

#### ?airqulity 하여 정보 확인.

## 5번문제 (답: 48일)

### summary(airquality 로 wind의 최대값 확인 후 subset으로 Wind 가 20.7의 값을 가지는 위치 탐색.)

### summary 대신 max 사용하여 최대값 확인해도 된다.
```{r}
summary(airquality)     # wind의 최대값은 20.700
max(airquality$Wind)

subset(airquality, Wind == 20.7)     # 48번째 행이 가장 바람이 강하게 분 날임.(20.700)
```

### 5번 문제 또 다른 방법 - which.max함수 사용.

```{r}
# ?which.max                           # 숫자(또는 논리) 벡터의 최소값 또는 최대값의 위치(예: 첫 번째)를 결정합니다.
which.max(airquality$Wind)           # 48.
```

## 6번문제(답: 44)

```{r}
table(is.na(airquality))  # table() 함수는 데이터의 빈도를 보여 준다.

sum(is.na(airquality))   # table 이용하지 않는 방법
```


## 7번문제

### 답: Locations of Earthquakes off Fiji

### ?quakes 하여 정보 확인.

## 8번문제

```{r}

max(quakes$mag)

```


### 다른방법: summary(quakes) 통해 mag의 최대값 확인
