---
title: 
author: "Soyeon Park"
date: '2021 4 23 '
output: html_document
---

# 4단원 단원문제

### 01번 1~100 수 중 3의 배수면서 4의 배수는 아닌 수의 합을 구하여라.
```{r}


x <- c(1:100)
sum(x[x%%3 == 0 & x%%4 != 0])

sum <- 0
for (i in 1:100) {
    if (i%%3 == 0 & i %% 4 != 0)
        sum <- sum + i
}
print(sum)
```


### x와 n을 입력하면 1부터 n까지의 수 중에서 x의 배수 합을 구해주는 사용자 정의 함수를 만들어라.
```{r}


mul_sum <- function(x, n) {
    sum <- 0
    for (i in 1:n) {
        if(i %% x == 0) {
            sum <- sum+i
        }
    }
    return(sum)
}

mul_sum(4, 16)

```



# install.packages("hflights")와 library(hflights) 명령어를 이용하여 hflights 데이터를 활용할 수 있게 하자. hflights 데이터에는 총 몇 개의 NA가 존재하는가?

```{r}
install.packages("hflights", repos = "http://cran.us.r-project.org")
library(hflights)

str(hflights)
sum(is.na(hflights))
```


### hflights 데이터에서 비행시간이 가장 긴 데이터는 몇 시간 몇 분인가?

```{r}
paste0(max(na.omit(hflights$AirTime)) %/% 60, "시간 ", max(na.omit(hflights$AirTime)) %% 60, "분")
```

### flights 데이터에서 비행거리가 가장 긴 데이터는 몇 마일인가?
```{r}

paste(max(na.omit(hflights$Distance)), "miles")
```

### hflights 데이터에서 비행편이 취소된 건수는 몇 건인가?

```{r}

class(hflights$Cancelled)

str(hflights$Cancelled)

sum(hflights$Cancelled)

```







